---
- name: Install IIS Web-Server with sub features and management tools
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: True
    include_management_tools: True
  register: win_feature
- name: Remove Default Web Site
  win_iis_website:
    name: "Default Web Site"
    state: absent
- name: return information about an existing application pool
  win_iis_webapppool:
    name: DefaultAppPool
    state: absent
